"""empty message

Revision ID: f48c79911b7f
Revises: e847f4426288
Create Date: 2022-07-27 22:56:08.465652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48c79911b7f'
down_revision = 'e847f4426288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'upcoming')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('upcoming', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
